name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Auto-fix code with Ruff
        run: |
          ruff format . --fix --line-length 88 --exclude migrations,venv || true

      - name: Run Ruff linter
        run: |
          ruff check . --select ALL --ignore F401,W391 --line-length 88
